### ISSUE TITLE
Can't resolve 'material-ui-pickers/utils/MuiPickersUtilsProvider'

### ISSUE THREAD

**Issue by petersg83** [vascofg/react-admin-date-inputs#15] opened 2018-10-31 01:18 UTC
Hello,

I installed _react-admin-dateinputs_ and I'm trying to use _TimeInput_ but I have this error:
`Module not found: Can't resolve 'material-ui-pickers/utils/MuiPickersUtilsProvider' in '/Users/pierre/Documents/schoolx/frontend/node_modules/react-admin-date-inputs/lib'`

Here is my package.json:

> {
>   "name": "schoolx-frontend",
>   "version": "0.1.0",
>   "private": true,
>   "dependencies": {
>     "import": "^0.0.6",
>     "jsonwebtoken": "^8.3.0",
>     "moment": "^2.22.2",
>     "ra-data-json-server": "^2.2.0",
>     "ra-language-english": "^2.2.0",
>     "ra-language-french": "^2.2.0",
>     "react": "^16.4.2",
>     "react-admin": "^2.4.0",
>     "react-admin-date-inputs": "^1.1.0",
>     "react-big-calendar": "^0.20.1",
>     "react-dom": "^16.4.2",
>     "react-router-dom": "^4.3.1",
>     "react-scripts": "1.1.4",
>     "recompose": "^0.28.2"
>   },
>   "scripts": {
>     "start": "react-scripts start",
>     "build": "react-scripts build",
>     "test": "react-scripts test --env=jsdom",
>     "eject": "react-scripts eject"
>   }
> }

I tried to install the module _material-ui-pickers_ but it didn't change anything.

Do you have an idea of how I can make it work ?
Thanks :)

**Comment by tmcgee** [comment] 2018-11-05 23:57
I am experiencing this as well. Likely related to the breaking changed noted in the material-ui-pickers version 1.0.0 [release notes](https://github.com/dmtrKovalenko/material-ui-pickers/releases/tag/v1.0.0):

``` diff
-import MuiPickersUtilsProvider from 'material-ui-pickers/utils/MuiPickersUtilsProvider'
+import MuiPickersUtilsProvider from 'material-ui-pickers/MuiPickersUtilsProvider'
```

**Comment by stephme** [comment] 2018-11-06 16:32
https://github.com/vascofg/react-admin-date-inputs/pull/16

**Comment by kent10ou** [comment] 2018-11-08 08:01
Thanks! Also facing same issue, is this change published to npm yet? Which version of material-ui is everyone else using?

**Comment by tmcgee** [comment] 2018-11-08 17:10
@kent10ou 

This might be related to yet-another-release of material-ui-pickers. Version [2.0.0](https://github.com/dmtrKovalenko/material-ui-pickers/releases/tag/v2.0.0) this time. From the release notes:

> We have moved our utils to the separate monorepo (star it [here](https://github.com/dmtrKovalenko/date-io)) and for now do

``` diff
-import Utils from 'material-ui-pickers/utils/date-fns-utils'
+import Utils from '@date-io/date-fns'
```

I haven't had the opportunity to verify/fix locally.

Hope this helps.

**Comment by romainquellec** [comment] 2018-11-21 14:04
@vascofg : Any plan to release a new version on npm ?

**Comment by marquesgabriel** [comment] 2018-11-27 19:45
watching this thread

**Comment by vascofg** [comment] 2018-11-27 20:53
Working on it now

**Comment by vascofg** [comment] 2018-11-27 21:59
> @kent10ou
> 
> This might be related to yet-another-release of material-ui-pickers. Version [2.0.0](https://github.com/dmtrKovalenko/material-ui-pickers/releases/tag/v2.0.0) this time. From the release notes:
> 
> > We have moved our utils to the separate monorepo (star it [here](https://github.com/dmtrKovalenko/date-io)) and for now do
> 
> ```diff
> -import Utils from 'material-ui-pickers/utils/date-fns-utils'
> +import Utils from '@date-io/date-fns'
> ```
> 
> [Here](https://github.com/vascofg/react-admin-date-inputs/blob/master/src/index.js#L5) is where I think the change should occur. I haven't had the opportunity to verify/fix locally.
> 
> Hope this helps.

Hey, unfortunately I won't be able to update to material-ui-pickers stable version since they decided to update to @material-ui/core@^3.2.0 and react-admin is still on @^1.4.0. This is causing some issues with the date-picker modal.

I'll try to publish a fixed version using the latest compatible material-ui-pickers version.

**Comment by vascofg** [comment] 2018-11-27 22:11
Fixed in 1.0.21

**Closed by vascofg** 2018-11-27 22:11 UTC

**Comment by mastox** [comment] 2019-01-04 17:23
Hey @vascofg, 
I have the same error message, but it's not solved in 1.0.21.

```json
  "dependencies": {
    "@material-ui/core": "^3.2.0",
    "jwt-decode": "^2.2.0",
    "material-ui-chip-input": "^0.19.0",
    "ra-data-json-server": "^2.5.2",
    "ra-data-simple-rest": "^2.5.2",
    "react": "^16.7.0",
    "react-admin": "^2.4.0",
    "react-admin-date-inputs": "^1.0.21",
    "react-dom": "^16.7.0",
    "react-scripts": "2.1.2"
  }

```
Is the version 1.0.21 compatible with the current version of @material-ui/core 3.2.0 ?
Thanks

**Comment by jacklj** [comment] 2019-01-10 00:21
I'm getting the error too:
```
Module not found: Error: Can't resolve 'date-fns/addDays' in '/tmp/build_768d2570a4572a43a5b79af1cef23b51/admin/node_modules/material-ui-pickers/utils'
```

Upgrading to 1.0.21 didn't help. 

Installing date-fns v2.0.0-alpha.7 manually *did* allow the app to build, but then I get weird visual bugs in the date picker, presumably due to breaking changes in version 2 of date-fns.

**Comment by despatates** [comment] 2019-10-23 10:46
It seems error `Can't resolve 'material-ui-pickers/utils/MuiPickersUtilsProvider'` is back.
May it be linked to the upgrade of `material-ui-pickers` in PR #31?

**Comment by despatates** [comment] 2019-10-28 09:38
An issue is open for this problem, see https://github.com/vascofg/react-admin-date-inputs/issues/37.

**Comment by x5engine** [comment] 2020-01-15 15:55
### 2020 

the issue is still happening :D

`Can't resolve 'material-ui-pickers/utils/MuiPickersUtilsProvider'`

I think it might be solved in 2070 for sure

**Comment by x5engine** [comment] 2020-01-15 16:17
anyway since the author is not here, here is a fix deployed to npm

https://github.com/x5engine/react-admin-date-inputs

`npm install react-admin-date-inputs2 --save`

**Comment by GaneshRasekar** [comment] 2020-03-29 08:57
![Capture](https://user-images.githubusercontent.com/22542344/77845028-2321bc00-71c9-11ea-8425-41b805c683ce.PNG)

issue in DateInput 
https://codesandbox.io/s/vigilant-diffie-lvn6v

**Comment by Julien-Sytadelle** [comment] 2020-04-30 11:26
Just in case : If you still use react-admin v2.9, simply use the version 1.1.2 code you can easily find in commit history (1 file) and change the pickers import:
import { MuiPickersUtilsProvider, DatePicker, TimePicker, DateTimePicker } from 'material-ui-pickers';
/*
import DatePicker from 'material-ui-pickers';
import TimePicker from 'material-ui-pickers';
import DateTimePicker from 'material-ui-pickers';
*/
